### ISSUE TITLE
Value of type 'SYMapView' has no member 'allMapObjects' 

### ISSUE THREAD

**Issue by NatashaApporio** [Sygic/sygic-maps-kit-ios#44]
To remove previously displayed map objects 
mapView.remove(_mapView.allMapObjects())
Used in delegate function  of SYRoutingDelegate
But getting error Value of type 'SYMapView' has no member 'allMapObjects' 

![Screen Shot 2019-06-21 at 3 40 38 PM](https://user-images.githubusercontent.com/43563955/59915890-531e8080-943b-11e9-9641-9b2b5940e8b0.png)

**Comment by jcaliksygic** [comment]
SYMapView's method allMapObjects was removed from SygicMaps interface from version 13.0.0. You should remember reference for every SYMapObjects added ty map by yourself.
